/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makanan;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.*;
import java.text.*;

/**
 *
 * @author asus
 */
public class Makan extends javax.swing.JFrame {

    /**
     * Creates new form Makan
     */
    public Makan() {
        initComponents();
            Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
               int x = layar.width / 2 - this.getSize().width / 2;
                    int y = layar.height / 2 - this.getSize().height / 2;
                    
                    this.setLocation(x,y);
        makantransac.setBackground(new Color(35,50,65,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Garlicbreadbox = new javax.swing.JCheckBox();
        txtGarlicbread = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ayambakarbox = new javax.swing.JCheckBox();
        txtAyambakar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Potatowadgesbox = new javax.swing.JCheckBox();
        txtPotatowadges = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Chickenwingsbox = new javax.swing.JCheckBox();
        txtChickenwings = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cheeserollbox = new javax.swing.JCheckBox();
        txtCheeseroll = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        makantransac = new javax.swing.JPanel();
        TotalPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelrequest2 = new javax.swing.JTextArea();
        tombolsavemakan = new javax.swing.JButton();
        tombolkeluarmakan = new javax.swing.JButton();
        tombolminum = new javax.swing.JButton();
        Hitung = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 40, 52));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/1554131962224.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 250, 260));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FOOD");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/garlic bread.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 240, 200));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 92, 220, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 260, 20));

        Garlicbreadbox.setBackground(new java.awt.Color(35, 45, 65));
        Garlicbreadbox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Garlicbreadbox.setForeground(new java.awt.Color(255, 255, 255));
        Garlicbreadbox.setText("GARLIC BREAD");
        Garlicbreadbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GarlicbreadboxActionPerformed(evt);
            }
        });
        jPanel1.add(Garlicbreadbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 130, -1));

        txtGarlicbread.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtGarlicbread.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGarlicbreadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtGarlicbreadMouseEntered(evt);
            }
        });
        txtGarlicbread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarlicbreadActionPerformed(evt);
            }
        });
        jPanel1.add(txtGarlicbread, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 50, 30));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RP. 20.000");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 690, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/Ayam.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 200, -1));

        Ayambakarbox.setBackground(new java.awt.Color(35, 45, 65));
        Ayambakarbox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Ayambakarbox.setForeground(new java.awt.Color(255, 255, 255));
        Ayambakarbox.setText("AYAM BAKAR MADU");
        Ayambakarbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyambakarboxActionPerformed(evt);
            }
        });
        jPanel1.add(Ayambakarbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 170, -1));

        txtAyambakar.setBorder(null);
        txtAyambakar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAyambakarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAyambakarMouseEntered(evt);
            }
        });
        jPanel1.add(txtAyambakar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 50, 30));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RP. 10.000");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/potato wadges.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        Potatowadgesbox.setBackground(new java.awt.Color(35, 45, 65));
        Potatowadgesbox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Potatowadgesbox.setForeground(new java.awt.Color(255, 255, 255));
        Potatowadgesbox.setText("POTATO WADGES");
        Potatowadgesbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotatowadgesboxActionPerformed(evt);
            }
        });
        jPanel1.add(Potatowadgesbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, -1, -1));

        txtPotatowadges.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        txtPotatowadges.setBorder(null);
        txtPotatowadges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPotatowadgesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPotatowadgesMouseEntered(evt);
            }
        });
        jPanel1.add(txtPotatowadges, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, 50, 30));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RP. 10.000");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/chicken wing.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, 160));

        Chickenwingsbox.setBackground(new java.awt.Color(35, 45, 65));
        Chickenwingsbox.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        Chickenwingsbox.setForeground(new java.awt.Color(255, 255, 255));
        Chickenwingsbox.setText("CHICKEN WINGS");
        Chickenwingsbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenwingsboxActionPerformed(evt);
            }
        });
        jPanel1.add(Chickenwingsbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 140, 30));

        txtChickenwings.setBorder(null);
        txtChickenwings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChickenwingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtChickenwingsMouseEntered(evt);
            }
        });
        txtChickenwings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChickenwingsActionPerformed(evt);
            }
        });
        jPanel1.add(txtChickenwings, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 690, 50, 30));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RP. 15.000");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 90, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/cheese roll.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        Cheeserollbox.setBackground(new java.awt.Color(35, 45, 65));
        Cheeserollbox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        Cheeserollbox.setForeground(new java.awt.Color(255, 255, 255));
        Cheeserollbox.setText("CHEESE ROLL");
        Cheeserollbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeserollboxActionPerformed(evt);
            }
        });
        jPanel1.add(Cheeserollbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 140, -1));

        txtCheeseroll.setBorder(null);
        txtCheeseroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCheeserollMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCheeserollMouseEntered(evt);
            }
        });
        txtCheeseroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheeserollActionPerformed(evt);
            }
        });
        jPanel1.add(txtCheeseroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 50, 30));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RP. 20.000");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 90, 30));

        makantransac.setBackground(new java.awt.Color(35, 50, 65));
        makantransac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalPrice.setBackground(new java.awt.Color(35, 60, 65));
        TotalPrice.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        TotalPrice.setForeground(new java.awt.Color(255, 255, 255));
        TotalPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalPriceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TotalPriceMouseEntered(evt);
            }
        });
        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });
        makantransac.add(TotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TOTAL HARGA");
        makantransac.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        panelrequest2.setBackground(new java.awt.Color(35, 60, 65));
        panelrequest2.setColumns(20);
        panelrequest2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelrequest2.setForeground(new java.awt.Color(255, 255, 255));
        panelrequest2.setRows(5);
        panelrequest2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(panelrequest2);

        makantransac.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 170));

        tombolsavemakan.setBackground(new java.awt.Color(153, 51, 0));
        tombolsavemakan.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        tombolsavemakan.setText("SAVE");
        tombolsavemakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsavemakanActionPerformed(evt);
            }
        });
        makantransac.add(tombolsavemakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 140, 40));

        tombolkeluarmakan.setBackground(new java.awt.Color(204, 0, 0));
        tombolkeluarmakan.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        tombolkeluarmakan.setText("KELUAR");
        tombolkeluarmakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkeluarmakanActionPerformed(evt);
            }
        });
        makantransac.add(tombolkeluarmakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 140, 40));

        tombolminum.setBackground(new java.awt.Color(153, 51, 0));
        tombolminum.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        tombolminum.setText("MINUMAN");
        tombolminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolminumActionPerformed(evt);
            }
        });
        makantransac.add(tombolminum, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 140, 40));

        Hitung.setBackground(new java.awt.Color(153, 153, 0));
        Hitung.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        makantransac.add(Hitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 140, 40));

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        makantransac.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 140, 40));

        jPanel1.add(makantransac, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 450, 300));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/food-1932466_1920 (2).jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -180, 1800, 1180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolsavemakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsavemakanActionPerformed
        save();
    }//GEN-LAST:event_tombolsavemakanActionPerformed

    private void tombolminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolminumActionPerformed
      minum();
    }//GEN-LAST:event_tombolminumActionPerformed

    private void tombolkeluarmakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkeluarmakanActionPerformed
    keluar();
    }//GEN-LAST:event_tombolkeluarmakanActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void txtChickenwingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChickenwingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChickenwingsActionPerformed

    private void GarlicbreadboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GarlicbreadboxActionPerformed
        if( Garlicbreadbox.isSelected()==true)
        {
            txtGarlicbread.setEditable(true);
            txtGarlicbread.requestFocus();
        }
        else 
        {
            txtGarlicbread.setEditable(false);
            txtGarlicbread.setText("");  
        }
    }//GEN-LAST:event_GarlicbreadboxActionPerformed

    private void AyambakarboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyambakarboxActionPerformed
        if( Ayambakarbox.isSelected()==true)
        {
            txtAyambakar.setEditable(true);
            txtAyambakar.requestFocus();
        }
        else 
        {
            txtAyambakar.setEditable(false);
            txtAyambakar.setText("");  
        }
    }//GEN-LAST:event_AyambakarboxActionPerformed

    private void CheeserollboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeserollboxActionPerformed
         if( Cheeserollbox.isSelected()==true)
        {
            txtCheeseroll.setEditable(true);
            txtCheeseroll.requestFocus();
        }
        else 
        {
            txtCheeseroll.setEditable(false);
            txtCheeseroll.setText("");  
        }
    }//GEN-LAST:event_CheeserollboxActionPerformed

    private void txtCheeserollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheeserollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheeserollActionPerformed

    private void PotatowadgesboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotatowadgesboxActionPerformed
       if( Potatowadgesbox.isSelected()==true)
        {
            txtPotatowadges.setEditable(true);
            txtPotatowadges.requestFocus();
        }
        else 
        {
            txtPotatowadges.setEditable(false);
            txtPotatowadges.setText("");  
        }
    }//GEN-LAST:event_PotatowadgesboxActionPerformed

    private void ChickenwingsboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenwingsboxActionPerformed
        if( Chickenwingsbox.isSelected()==true)
        {
            txtChickenwings.setEditable(true);
            txtChickenwings.requestFocus();
        }
        else 
        {
            txtChickenwings.setEditable(false);
            txtChickenwings.setText("");  
        }
    }//GEN-LAST:event_ChickenwingsboxActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
      hitung();
    }//GEN-LAST:event_HitungActionPerformed

    private void txtGarlicbreadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGarlicbreadMouseEntered
            
            txtGarlicbread.setText("");  
    }//GEN-LAST:event_txtGarlicbreadMouseEntered

    private void txtGarlicbreadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGarlicbreadMouseClicked
            
            txtGarlicbread.setText(""); 
    }//GEN-LAST:event_txtGarlicbreadMouseClicked

    private void txtAyambakarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAyambakarMouseEntered
            
            txtAyambakar.setText("");
    }//GEN-LAST:event_txtAyambakarMouseEntered

    private void txtAyambakarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAyambakarMouseClicked
            
            txtAyambakar.setText("");
    }//GEN-LAST:event_txtAyambakarMouseClicked

    private void txtCheeserollMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCheeserollMouseEntered
     
        txtCheeseroll.setText("");
    }//GEN-LAST:event_txtCheeserollMouseEntered

    private void txtCheeserollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCheeserollMouseClicked
            
            txtCheeseroll.setText("");
    }//GEN-LAST:event_txtCheeserollMouseClicked

    private void txtPotatowadgesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPotatowadgesMouseEntered
     
        txtPotatowadges.setText("");
    }//GEN-LAST:event_txtPotatowadgesMouseEntered

    private void txtPotatowadgesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPotatowadgesMouseClicked
         
        txtPotatowadges.setText("");
    }//GEN-LAST:event_txtPotatowadgesMouseClicked

    private void txtChickenwingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChickenwingsMouseEntered
       
        txtChickenwings.setText("");
    }//GEN-LAST:event_txtChickenwingsMouseEntered

    private void txtChickenwingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChickenwingsMouseClicked
        
        txtChickenwings.setText("");
    }//GEN-LAST:event_txtChickenwingsMouseClicked

    private void TotalPriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalPriceMouseEntered
        TotalPrice.setEditable(false);
    }//GEN-LAST:event_TotalPriceMouseEntered

    private void TotalPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalPriceMouseClicked
        TotalPrice.setEditable(false);
    }//GEN-LAST:event_TotalPriceMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
               
       this.setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void txtGarlicbreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarlicbreadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarlicbreadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Makan().setVisible(true);
        });
    }    
        public void hitung()
        {
              
        int HrgGarlicBread =0;
        int HrgAyamBakar =0;
        int HrgCheeseRoll =0;
        int HrgPotatoWadges =0;
        int HrgChickenWings =0;
        int total =0;
        if(Garlicbreadbox.isSelected()== false && Ayambakarbox.isSelected()==false
            && Cheeserollbox.isSelected()==false && Potatowadgesbox.isSelected()==false
            && Chickenwingsbox.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Makanan belum dipesan","Warning",JOptionPane.WARNING_MESSAGE);
        }
         else 
        {
            if(Garlicbreadbox.isSelected() == true)
            {
                String GB =txtGarlicbread.getText();
                    int jmlGB =Integer.parseInt(GB);
                    HrgGarlicBread =jmlGB*10000;
                    total = total+HrgGarlicBread;
            }
            
            if(Ayambakarbox.isSelected() == true)
            {
                    String AB =txtAyambakar.getText();
                    int jmlAB =Integer.parseInt(AB);
                    HrgAyamBakar =jmlAB*20000;
                    total =total+HrgAyamBakar;
            }
            
            if(Cheeserollbox.isSelected() == true)
            {
                    String CR =txtCheeseroll.getText();
                    int jmlCR =Integer.parseInt(CR);
                    HrgCheeseRoll =jmlCR*15000;
                    total = total+HrgCheeseRoll;
            }
            
            if(Potatowadgesbox.isSelected() == true)
            {
                   String PW =txtPotatowadges.getText();
                    int jmlPW =Integer.parseInt(PW);
                    HrgPotatoWadges =jmlPW*10000;
                    total =total+HrgPotatoWadges;
            }
            
            if(Chickenwingsbox.isSelected() == true)
            {
                    String CW =txtChickenwings.getText();
                    int jmltCW =Integer.parseInt(CW);
                    HrgChickenWings =jmltCW*20000;
                    total = total+HrgChickenWings;
            }
        }
        TotalPrice.setText("Rp. " +total+",00");
        
        }
        
        public int totalgb (int gb, int qty) { //total harga garlic bread
        return gb*qty;
    }
    
    public int totalab (int ab, int qty) { //total harga ayam bakar
        return ab*qty;
    }
    
    public int totalcs (int cs, int qty) { //total harga cheeseroll
        return cs*qty;
    }
    
    public int totalpw (int pw, int qty) { //total harga potato wedges
        return pw*qty;
    }
    
    public int totalcw (int cw, int qty) { //total harga chicken wings
        return cw*qty;
    }
        
        public void save()
        {
            String request;
        request= panelrequest2.getText();
            if (request.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Pesanan Diterima");
                int selectedOption = JOptionPane.showConfirmDialog(null,"Ingin Pesan Minuman?","Order Form",JOptionPane.YES_NO_OPTION);
                    if (selectedOption==JOptionPane.YES_OPTION)
                    {
                         Minuman A = new Minuman();
                         A.setVisible(true);
                         this.setVisible(false);
                    }
                    else
                    {
                         Register A = new Register();
                         A.setVisible(true);
                         this.setVisible(false);
                    }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Pesanan Anda Diterima");
                int selectedOption = JOptionPane.showConfirmDialog(null,"Ingin Pesan Minuman?","Order Form",JOptionPane.YES_NO_OPTION);
                    if (selectedOption==JOptionPane.YES_OPTION)
                    {
                          Minuman A = new Minuman();
                         A.setVisible(true);
                         this.setVisible(false);
                    }
                         else
                    {
                         Register A = new Register();
                         A.setVisible(true);
                         this.setVisible(false);
                    }
            }
        }
        
        public void keluar()
        {
            int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
            if(selectedOption==JOptionPane.YES_OPTION){
            Register A = new Register();
            A.setVisible(true);
            this.setVisible(false);
        }
        }
        
        public void minum()
        {
             Minuman A = new Minuman();
            A.setVisible(true);
            this.setVisible(false);
        }
        public void hapus()
        {
        String test;
        TotalPrice.setText("");
        panelrequest2.setText(""); 
        txtPotatowadges.setText("");
        txtAyambakar.setText("");
        txtChickenwings.setText("");
        txtGarlicbread.setText("");
        txtCheeseroll.setText("");
        Ayambakarbox.setSelected(false);
        Cheeserollbox.setSelected(false);
        Chickenwingsbox.setSelected(false);
        Garlicbreadbox.setSelected(false);
        Potatowadgesbox.setSelected(false);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Ayambakarbox;
    private javax.swing.JCheckBox Cheeserollbox;
    private javax.swing.JCheckBox Chickenwingsbox;
    private javax.swing.JCheckBox Garlicbreadbox;
    private javax.swing.JButton Hitung;
    private javax.swing.JCheckBox Potatowadgesbox;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel makantransac;
    private javax.swing.JTextArea panelrequest2;
    private javax.swing.JButton tombolkeluarmakan;
    private javax.swing.JButton tombolminum;
    private javax.swing.JButton tombolsavemakan;
    private javax.swing.JTextField txtAyambakar;
    private javax.swing.JTextField txtCheeseroll;
    private javax.swing.JTextField txtChickenwings;
    private javax.swing.JTextField txtGarlicbread;
    private javax.swing.JTextField txtPotatowadges;
    // End of variables declaration//GEN-END:variables
}
