/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package makanan;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author asus
 */
public class Minuman extends javax.swing.JFrame {

    /**
     * Creates new form Minuman
     */
    public Minuman() {
        initComponents();
            Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
                int x = layar.width / 2 - this.getSize().width / 2;
                    int y = layar.height / 2 - this.getSize().height / 2;
                    
                    this.setLocation (x,y);
        panelminum.setBackground(new Color(51,51,51,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caramellattebox = new javax.swing.JCheckBox();
        txtCaramellatte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tropicalpunchbox = new javax.swing.JCheckBox();
        txtTropicalpunch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cappucinobox = new javax.swing.JCheckBox();
        txtCappucino = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        americanobox = new javax.swing.JCheckBox();
        txtAmericano = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lycheebreezebox = new javax.swing.JCheckBox();
        txtLycheebreeze = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        panelminum = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Totalharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelrequest = new javax.swing.JTextArea();
        tombolsaveminum = new javax.swing.JButton();
        tombolmakan = new javax.swing.JButton();
        tombolkeluarminum = new javax.swing.JButton();
        HITUNG = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 45, 65));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 300, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/Americano.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 220));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BEVERAGE");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, 60));

        caramellattebox.setBackground(new java.awt.Color(153, 153, 153));
        caramellattebox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        caramellattebox.setForeground(new java.awt.Color(255, 255, 255));
        caramellattebox.setText("CARAMEL LATTE");
        caramellattebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramellatteboxActionPerformed(evt);
            }
        });
        jPanel1.add(caramellattebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 150, 20));

        txtCaramellatte.setBorder(null);
        txtCaramellatte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCaramellatteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCaramellatteMouseEntered(evt);
            }
        });
        txtCaramellatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaramellatteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCaramellatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 50, 30));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/cappucino.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 160, 200));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/caramel latte.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 140, 210));

        tropicalpunchbox.setBackground(new java.awt.Color(153, 153, 153));
        tropicalpunchbox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        tropicalpunchbox.setForeground(new java.awt.Color(255, 255, 255));
        tropicalpunchbox.setText("TROPICAL PUNCH");
        tropicalpunchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tropicalpunchboxActionPerformed(evt);
            }
        });
        jPanel1.add(tropicalpunchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, 150, 20));

        txtTropicalpunch.setBorder(null);
        txtTropicalpunch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTropicalpunchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTropicalpunchMouseEntered(evt);
            }
        });
        jPanel1.add(txtTropicalpunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 50, 30));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/tropical punch.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 180, 210));

        cappucinobox.setBackground(new java.awt.Color(153, 153, 153));
        cappucinobox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cappucinobox.setForeground(new java.awt.Color(255, 255, 255));
        cappucinobox.setText("CAPPUCINO");
        cappucinobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappucinoboxActionPerformed(evt);
            }
        });
        jPanel1.add(cappucinobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 120, 20));

        txtCappucino.setBorder(null);
        txtCappucino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCappucinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCappucinoMouseEntered(evt);
            }
        });
        txtCappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCappucinoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 50, 30));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/lychee breeze.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 160, 210));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/1554131962224.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 250, 250));

        americanobox.setBackground(new java.awt.Color(153, 153, 153));
        americanobox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        americanobox.setForeground(new java.awt.Color(255, 255, 255));
        americanobox.setText("AMERICANO");
        americanobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanoboxActionPerformed(evt);
            }
        });
        jPanel1.add(americanobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 120, 20));

        txtAmericano.setBorder(null);
        txtAmericano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAmericanoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAmericanoMouseEntered(evt);
            }
        });
        jPanel1.add(txtAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 50, 30));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RP. 7000");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 90, 30));

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RP. 5000");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 90, 30));

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RP. 5000");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 90, 30));

        lycheebreezebox.setBackground(new java.awt.Color(153, 153, 153));
        lycheebreezebox.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lycheebreezebox.setForeground(new java.awt.Color(255, 255, 255));
        lycheebreezebox.setText("LYCHEE BREEZE");
        lycheebreezebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lycheebreezeboxActionPerformed(evt);
            }
        });
        jPanel1.add(lycheebreezebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 650, 150, 20));

        txtLycheebreeze.setBorder(null);
        txtLycheebreeze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLycheebreezeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLycheebreezeMouseEntered(evt);
            }
        });
        jPanel1.add(txtLycheebreeze, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 50, 30));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("RP. 5000");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 680, 90, 30));

        panelminum.setBackground(new java.awt.Color(102, 102, 102));
        panelminum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RP. 8000");
        panelminum.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 90, 30));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("TOTAL HARGA");
        panelminum.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 30));

        Totalharga.setBackground(new java.awt.Color(51, 51, 51));
        Totalharga.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        Totalharga.setForeground(new java.awt.Color(255, 255, 255));
        Totalharga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalhargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TotalhargaMouseEntered(evt);
            }
        });
        Totalharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalhargaActionPerformed(evt);
            }
        });
        panelminum.add(Totalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 40));

        panelrequest.setBackground(new java.awt.Color(51, 51, 51));
        panelrequest.setColumns(20);
        panelrequest.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        panelrequest.setForeground(new java.awt.Color(255, 255, 255));
        panelrequest.setRows(5);
        jScrollPane1.setViewportView(panelrequest);

        panelminum.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 170));

        tombolsaveminum.setBackground(new java.awt.Color(153, 51, 0));
        tombolsaveminum.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        tombolsaveminum.setText("SAVE");
        tombolsaveminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolsaveminumActionPerformed(evt);
            }
        });
        panelminum.add(tombolsaveminum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 140, 40));

        tombolmakan.setBackground(new java.awt.Color(153, 51, 0));
        tombolmakan.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        tombolmakan.setText("MAKANAN");
        tombolmakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolmakanActionPerformed(evt);
            }
        });
        panelminum.add(tombolmakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, 40));

        tombolkeluarminum.setBackground(new java.awt.Color(204, 0, 0));
        tombolkeluarminum.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        tombolkeluarminum.setText("KELUAR");
        tombolkeluarminum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkeluarminumActionPerformed(evt);
            }
        });
        panelminum.add(tombolkeluarminum, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 140, 40));

        HITUNG.setBackground(new java.awt.Color(153, 153, 0));
        HITUNG.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        HITUNG.setText("HITUNG");
        HITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HITUNGActionPerformed(evt);
            }
        });
        panelminum.add(HITUNG, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 140, 40));

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelminum.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 140, 40));

        jPanel1.add(panelminum, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 460, 310));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("RP. 8000");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 90, 30));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("RP. 5000");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 90, 30));

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/coffee-869203_1920 (2).png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCaramellatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaramellatteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaramellatteActionPerformed

    private void txtCappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCappucinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCappucinoActionPerformed

    private void tropicalpunchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tropicalpunchboxActionPerformed
       if( tropicalpunchbox.isSelected()==true)
        {
            txtTropicalpunch.setEditable(true);
            txtTropicalpunch.requestFocus();
        }
        else 
        {
            txtTropicalpunch.setEditable(false);
            txtTropicalpunch.setText("");  
        }
    }//GEN-LAST:event_tropicalpunchboxActionPerformed

    private void lycheebreezeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lycheebreezeboxActionPerformed
        if( lycheebreezebox.isSelected()==true)
        {
            txtLycheebreeze.setEditable(true);
            txtLycheebreeze.requestFocus();
        }
        else 
        {
            txtLycheebreeze.setEditable(false);
            txtLycheebreeze.setText("");  
        }
    }//GEN-LAST:event_lycheebreezeboxActionPerformed

    private void tombolsaveminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolsaveminumActionPerformed
         save();
    }//GEN-LAST:event_tombolsaveminumActionPerformed

    private void tombolmakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolmakanActionPerformed
       makan();
    }//GEN-LAST:event_tombolmakanActionPerformed

    private void tombolkeluarminumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkeluarminumActionPerformed
        keluar();
    }//GEN-LAST:event_tombolkeluarminumActionPerformed

    private void americanoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanoboxActionPerformed
       if( americanobox.isSelected()==true)
        {
            txtAmericano.setEditable(true);
            txtAmericano.requestFocus();
        }
        else 
        {
            txtAmericano.setEditable(false);
            txtAmericano.setText("");  
        }
    }//GEN-LAST:event_americanoboxActionPerformed

    private void cappucinoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappucinoboxActionPerformed
        if( cappucinobox.isSelected()==true)
        {
            txtCappucino.setEditable(true);
            txtCappucino.requestFocus();
        }
        else 
        {
            txtCappucino.setEditable(false);
            txtCappucino.setText("");  
        }
    }//GEN-LAST:event_cappucinoboxActionPerformed

    private void caramellatteboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramellatteboxActionPerformed
         if( caramellattebox.isSelected()==true)
        {
            txtCaramellatte.setEditable(true);
            txtCaramellatte.requestFocus();
        }
        else 
        {
            txtCaramellatte.setEditable(false);
            txtCaramellatte.setText("");  
        }
    }//GEN-LAST:event_caramellatteboxActionPerformed

    private void HITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HITUNGActionPerformed
        hitung();
    }//GEN-LAST:event_HITUNGActionPerformed

    private void txtAmericanoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmericanoMouseEntered
           
            txtAmericano.setText("");  
    }//GEN-LAST:event_txtAmericanoMouseEntered

    private void txtAmericanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAmericanoMouseClicked
            
            txtAmericano.setText("");  
    }//GEN-LAST:event_txtAmericanoMouseClicked

    private void txtCappucinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCappucinoMouseEntered
            
            txtCappucino.setText("");  
    }//GEN-LAST:event_txtCappucinoMouseEntered

    private void txtCappucinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCappucinoMouseClicked
           
            txtCappucino.setText("");  
    }//GEN-LAST:event_txtCappucinoMouseClicked

    private void txtCaramellatteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaramellatteMouseEntered
           
            txtCaramellatte.setText("");  
    }//GEN-LAST:event_txtCaramellatteMouseEntered

    private void txtCaramellatteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaramellatteMouseClicked
           
            txtCaramellatte.setText("");  
    }//GEN-LAST:event_txtCaramellatteMouseClicked

    private void txtLycheebreezeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLycheebreezeMouseEntered
            
            txtLycheebreeze.setText("");  
    }//GEN-LAST:event_txtLycheebreezeMouseEntered

    private void txtLycheebreezeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLycheebreezeMouseClicked
           
            txtLycheebreeze.setText("");  
    }//GEN-LAST:event_txtLycheebreezeMouseClicked

    private void txtTropicalpunchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTropicalpunchMouseEntered
           
            txtTropicalpunch.setText("");  
    }//GEN-LAST:event_txtTropicalpunchMouseEntered

    private void txtTropicalpunchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTropicalpunchMouseClicked
          
            txtTropicalpunch.setText("");  
    }//GEN-LAST:event_txtTropicalpunchMouseClicked

    private void TotalhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalhargaActionPerformed
        Totalharga.setEditable(false);
    }//GEN-LAST:event_TotalhargaActionPerformed

    private void TotalhargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalhargaMouseEntered
       Totalharga.setEditable(false);
    }//GEN-LAST:event_TotalhargaMouseEntered

    private void TotalhargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalhargaMouseClicked
         Totalharga.setEditable(false);
    }//GEN-LAST:event_TotalhargaMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
               
        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Minuman().setVisible(true);
        });
    }
    
    public void hitung()
    {
        int HrgAmericano =0;
        int HrgCappucino =0;
        int HrgCaramelLatte =0;
        int HrgLycheeBreeze =0;
        int HrgTropicalPunch =0;
        int total =0;
        if(americanobox.isSelected()== false && cappucinobox.isSelected()==false
            && caramellattebox.isSelected()==false && lycheebreezebox.isSelected()==false
            && tropicalpunchbox.isSelected() ==false)
        {
            JOptionPane.showMessageDialog(null,"Makanan belum dipesan","Warning",JOptionPane.WARNING_MESSAGE);
        }
         else 
        {
            if(americanobox.isSelected() == true)
            {
                String am =txtAmericano.getText();
                    int jmlam =Integer.parseInt(am);
                    HrgAmericano =jmlam*5000;
                    total = total+HrgAmericano;
            }
            
            if(cappucinobox.isSelected() == true)
            {
                    String cap =txtCappucino.getText();
                    int jmlcap =Integer.parseInt(cap);
                    HrgCappucino =jmlcap*7000;
                    total =total+HrgCappucino;
            }
            
            if(caramellattebox.isSelected() == true)
            {
                    String car =txtCaramellatte.getText();
                    int jmlcar =Integer.parseInt(car);
                    HrgCaramelLatte =jmlcar*8000;
                    total = total+HrgCaramelLatte;
            }
            
            if(lycheebreezebox.isSelected() == true)
            {
                   String lyc =txtLycheebreeze.getText();
                    int jmllyc =Integer.parseInt(lyc);
                    HrgLycheeBreeze =jmllyc*5000;
                    total =total+HrgLycheeBreeze;
            }
            
            if(tropicalpunchbox.isSelected() == true)
            {
                    String tcp =txtTropicalpunch.getText();
                    int jmltcp =Integer.parseInt(tcp);
                    HrgTropicalPunch =jmltcp*5000;
                    total = total+HrgTropicalPunch;
            }
        }
        Totalharga.setText("Rp. " +total+",00");
    }
    
    public int totalab (int ab, int qty){ //total americano box
        return ab*qty;
    }
    
    public int totalcb (int cb, int qty){ //total cappucinno box
        return cb*qty;
    }
    
    public int totalcl (int cl, int qty) { //total caramel latte
        return cl*qty;
    }
    
    public int totallb (int lb, int qty){ //total lychee breeze
        return lb*qty;
    }
    
    public int totaltp (int tp, int qty){ //total tropical punch
        return tp*qty;
    }
    
    public void keluar()
    {
        int selectedOption = JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Keluar?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
        if(selectedOption==JOptionPane.YES_OPTION)
        {
            Register A = new Register();
            A.setVisible(true);
            this.setVisible(false);
        }
    }
    
    public void makan()
    {
        Makan A = new Makan();
       A.setVisible(true);
       this.setVisible(false);
    }
    
    public void save()
    {
         String request;
        request= panelrequest.getText();
            if (request.equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Pesanan Diterima");
                 JOptionPane.showMessageDialog(null,"Terima kasih Telah Memesan di Fakultas Kopi");
                        Register A = new Register();
                         A.setVisible(true);
                         this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Pesanan Anda Diterima");
                 JOptionPane.showMessageDialog(null,"Terima kasih Telah Memesan di Fakultas Kopi");
                        Register A = new Register();
                         A.setVisible(true);
                         this.setVisible(false);
            }
    }
    
    public void hapus()
    {
        
        Totalharga.setText("");
        panelrequest.setText(""); 
        txtAmericano.setText("");
        txtCappucino.setText("");
        txtCaramellatte.setText("");
        txtLycheebreeze.setText("");
        txtTropicalpunch.setText("");
        americanobox.setSelected(false);
        cappucinobox.setSelected(false);
        caramellattebox.setSelected(false);
        lycheebreezebox.setSelected(false);
        tropicalpunchbox.setSelected(false);
        
        
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HITUNG;
    private javax.swing.JTextField Totalharga;
    private javax.swing.JCheckBox americanobox;
    private javax.swing.JCheckBox cappucinobox;
    private javax.swing.JCheckBox caramellattebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox lycheebreezebox;
    private javax.swing.JPanel panelminum;
    private javax.swing.JTextArea panelrequest;
    private javax.swing.JButton tombolkeluarminum;
    private javax.swing.JButton tombolmakan;
    private javax.swing.JButton tombolsaveminum;
    private javax.swing.JCheckBox tropicalpunchbox;
    private javax.swing.JTextField txtAmericano;
    private javax.swing.JTextField txtCappucino;
    private javax.swing.JTextField txtCaramellatte;
    private javax.swing.JTextField txtLycheebreeze;
    private javax.swing.JTextField txtTropicalpunch;
    // End of variables declaration//GEN-END:variables
}

