package makanan;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

public class Register extends javax.swing.JFrame 
{
    String userlogin;
    String passlogin;
    String Emaillogin;
    
    public Register() 
    {
        initComponents();
               
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Userlog = new javax.swing.JTextField();
        Passlog = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loginbottom = new javax.swing.JButton();
        panellogo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(36, 40, 52));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(49, 54, 74));
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN FORM");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, 50));

        Userlog.setFont(new java.awt.Font("Nirmala UI", 0, 18)); // NOI18N
        Userlog.setForeground(new java.awt.Color(153, 153, 153));
        Userlog.setText("Username");
        Userlog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Userlog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserlogMouseClicked(evt);
            }
        });
        Userlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserlogActionPerformed(evt);
            }
        });
        jPanel4.add(Userlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 360, 60));

        Passlog.setForeground(new java.awt.Color(153, 153, 153));
        Passlog.setText("Input Password");
        Passlog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Passlog.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasslogFocusGained(evt);
            }
        });
        Passlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasslogActionPerformed(evt);
            }
        });
        jPanel4.add(Passlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 360, 60));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Whatssapp: 0897667755443");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 180, 20));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("This is Unoffical Facultas Kopi Web");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 220, 20));

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Facebook : FAKULTAS KOPI JAKARTA");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 260, 20));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Instagram: FAKULTAS KOPI");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 190, 20));

        loginbottom.setBackground(new java.awt.Color(255, 102, 0));
        loginbottom.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        loginbottom.setText("LOGIN");
        loginbottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbottomActionPerformed(evt);
            }
        });
        jPanel4.add(loginbottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 130, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 530, 610));

        panellogo.setPreferredSize(new java.awt.Dimension(250, 250));
        panellogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("jLabel3");
        panellogo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 440, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/1554131962224.png"))); // NOI18N
        panellogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 250));

        jPanel2.add(panellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 250, 250));

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel3);

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 40, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/makanan/black-coffee-1868462_1280.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 770));
        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x, y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void PasslogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasslogActionPerformed
        Passlog.setText("");
    }//GEN-LAST:event_PasslogActionPerformed

    private void PasslogFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasslogFocusGained
        Passlog.setText("");
    }//GEN-LAST:event_PasslogFocusGained

    private void UserlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserlogActionPerformed
        Userlog.setText("");
    }//GEN-LAST:event_UserlogActionPerformed

    private void UserlogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserlogMouseClicked
        Userlog.setText("");
    }//GEN-LAST:event_UserlogMouseClicked

    private void loginbottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbottomActionPerformed
login(Userlog.getText(), Passlog.getText());
    }//GEN-LAST:event_loginbottomActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
    int exit = JOptionPane.showConfirmDialog(null,"Ingin Keluar?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
    if (exit == JOptionPane.YES_OPTION)
        {
          System.exit(0);
        }
    }//GEN-LAST:event_jPanel6MouseClicked
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int exit = JOptionPane.showConfirmDialog(null,"Ingin Keluar?","Tutup Aplikasi",JOptionPane.YES_NO_OPTION);
            if (exit == JOptionPane.YES_OPTION)
                {
                  System.exit(0);
                }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passlog;
    private javax.swing.JTextField Userlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton loginbottom;
    private javax.swing.JPanel panellogo;
    // End of variables declaration//GEN-END:variables

    public String login(String uname, String pword) {
        String u = "admin";
        String p = "admin123";

        if (uname.equals(u) && p.equalsIgnoreCase(p)) {
            JOptionPane.showMessageDialog(null, "Anda Sukses Masuk");
            this.setVisible(false);
            new Makan().setVisible(true);
            return u;
        } else {
            JOptionPane.showMessageDialog(null, "Anda gagal Login");
            Userlog.setText("");
            Passlog.setText("");
            Userlog.requestFocus();
            return null;
        }
    }
    
}
